# Generated by Django 2.2 on 2020-04-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20200415_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
